
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abe Fehr
email: abe.fehr@gmail.com
description: I'm a student of <a href="https://en.wikipedia.org/wiki/Computer_science/">Computer Science</a> completing my final year at <a href="https://carleton.ca/">Carleton University</a> in Ottawa, Canada. I enjoy many facets of Computer Science and Mathematics including Software Engineering, Algorithms, and Computer Graphics. As part of a work-study program I've worked at <a href="http://www.ibm.com/ca-en/">IBM</a> and <a href="http://ca.blackberry.com/home.html">BlackBerry</a>, and <a href="https://www.studeersnel.nl/">StudeerSnel</a>.
url: "https://abefehr.com" # the base hostname & protocol for your site
github_username: abejfehr

# Build settings
markdown: kramdown
# I don't really wanna use Jekyll
include:
  - .nojekyll
exclude:
  - "Rakefile"
  - "Gruntfile.coffee"
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"
